### ISSUE TITLE
Amazing project but...

### ISSUE THREAD

**Issue by Zaxuhe** [xorentor/dota2harvester#1]
Hello I would like to help you, you should make a tutorial on how you find these memory addresses so we can help you to stay updated, I will try to do it, but a tutorial should help! thanks :D

**Comment by Zaxuhe** [comment]
Also I always find client.dll at the same address why is that?

**Comment by xorentor** [comment]
hi there, I've just updated offsets, plz send me an email so I can give you further instructions xorentor at gmailcom
