### ISSUE TITLE
Wrong offsets everywhere

### ISSUE THREAD

**Issue by WilcoKruijer** [xorentor/dota2harvester#2]
There seem to be wrong offsets everywhere. This is an example output I get from a random DotaTv game http://hastebin.com/aduyeheveb. Only the last part of the names are shown, and the data isn't correct at all. The first player "erade" (Actually "@Masquerade") is playing Invoker, not Dark Seer as the dump suggests, all other information of that player seems to be Dark Seer's information as well. All player information seems to be shifted. Item and tower information all show 0.

Edit: I guess it's because I'm on 64 bit? If so ignore everything :cold_sweat:

**Comment by xorentor** [comment]
hi there, everytime dota2.exe is recompiled those offsets change, I've just updated them, so they will last for a couple of days
