### ISSUE TITLE
Textfile output

### ISSUE THREAD

**Issue by dMoelishR** [xorentor/dota2harvester#3]
Hi,
I would like to ask if you can release a version, that simply puts all the information it can harvest in a .txt, so other programs can simply open the txt and get out the needed information. 
Why? I usually dont code in C and dont really understand it, but I really need something exactly like this project, so this would really, really help me out. I would even pay for it.

**Comment by WilcoKruijer** [comment]
Use
d2h.exe > output.txt

**Comment by xorentor** [comment]
hi dMoelishR, that's exactly how it's done. there is an output file called 'gamedata' that is located in the same directory as d2h.exe when it runs correctly. Optionally you can send that file to network
